# Generated by Django 4.0.4 on 2022-06-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamehundred', '0002_remove_game_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='number_cur',
            new_name='number_init',
        ),
    ]
