# Generated by Django 4.0.4 on 2022-08-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamehundred', '0003_rename_number_cur_game_number_init'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='number_magic',
        ),
        migrations.RemoveField(
            model_name='game',
            name='number_max_avail',
        ),
        migrations.AddField(
            model_name='game',
            name='max_avail',
            field=models.IntegerField(default=10, help_text='Maximal available integer'),
        ),
    ]
